# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20160710_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200)),
                ('kind', models.CharField(max_length=12)),
                ('num_lines', models.IntegerField()),
            ],
        ),
    ]
