# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-04 22:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_add-sourcefile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sourcefile",
            old_name="kind",
            new_name="language",
        ),
    ]
