# Generated by Django 3.2.5 on 2021-07-10 16:44

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0021_symbol"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="skeleton",
            name="sourceline",
        ),
        migrations.AddField(
            model_name="skeleton",
            name="symbol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.symbol",
            ),
        ),
        migrations.AlterField(
            model_name="skeleton",
            name="color",
            field=colorfield.fields.ColorField(default="#FFFFFF", max_length=18),
        ),
    ]
