graph TD
dnsmasq --> contrib/lease-tools/dhcp_lease_time.c
dnsmasq --> contrib/lease-tools/dhcp_release.c
dnsmasq --> contrib/lease-tools/dhcp_release6.c
dnsmasq --> src/arp.c
dnsmasq --> src/auth.c
dnsmasq --> src/blockdata.c
dnsmasq --> src/bpf.c
dnsmasq --> src/cache.c
dnsmasq --> src/conntrack.c
dnsmasq --> src/crypto.c
dnsmasq --> src/dbus.c
dnsmasq --> src/dhcp-common.c
dnsmasq --> src/dhcp.c
dnsmasq --> src/dhcp6.c
dnsmasq --> src/dnsmasq.c
dnsmasq --> src/dnssec.c
dnsmasq --> src/domain.c
dnsmasq --> src/dump.c
dnsmasq --> src/edns0.c
dnsmasq --> src/forward.c
dnsmasq --> src/helper.c
dnsmasq --> src/inotify.c
dnsmasq --> src/ipset.c
dnsmasq --> src/lease.c
dnsmasq --> src/log.c
dnsmasq --> src/loop.c
dnsmasq --> src/metrics.c
dnsmasq --> src/netlink.c
dnsmasq --> src/network.c
dnsmasq --> src/option.c
dnsmasq --> src/outpacket.c
dnsmasq --> src/poll.c
dnsmasq --> src/radv.c
dnsmasq --> src/rfc1035.c
dnsmasq --> src/rfc2131.c
dnsmasq --> src/rfc3315.c
dnsmasq --> src/rrfilter.c
dnsmasq --> src/slaac.c
dnsmasq --> src/tables.c
dnsmasq --> src/tftp.c
dnsmasq --> src/ubus.c
dnsmasq --> src/util.c